apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-war-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-war-app
  template:
    metadata:
      labels:
        app: maven-war-app
    spec:
      containers:
      - name: maven-war-app
        image: 770651355673.dkr.ecr.ap-south-1.amazonaws.com/maven-war-app:IMAGE_TAG
        ports:
        - containerPort: 8080
