name: CD-DEPLOY-EKS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI-BUILD-IMAGE"]
    types:
      - completed

jobs:
  CD:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, MDP]

    steps:
      # Checkout application source
      - name: Checkout repo
        uses: actions/checkout@v4

      # Download image tag artifact from CI
      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Read image tag into environment
      - name: Read image tag
        run: |
          IMAGE_TAG=$(cat image-tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Using IMAGE_TAG=$IMAGE_TAG"

      # Generate kubeconfig using EC2 IAM role (EKS-Admin-Role)
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name EKS-cluster

      # Optional but highly recommended sanity check
      - name: Verify EKS access
        run: kubectl get nodes

      # Deploy Kubernetes manifests
      - name: Deploy to EKS
        run: |
          envsubst < k8s/deployment.yaml | kubectl apply -f -
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
