name: CI-CD-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  BUILD:
    runs-on: [self-hosted, MDP]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - name: Build with Maven
        run: mvn clean package
        
      - name: Deploy WAR to Tomcat
        env:
          TOMCAT_URL: ${{ secrets.TOMCAT_URL }}
          TOMCAT_USER: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASS: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          WAR=$(ls target/*.war | head -n 1)
          curl -sS -u "${TOMCAT_USER}:${TOMCAT_PASS}" --upload-file "$WAR" "${TOMCAT_URL}/manager/text/deploy?path=/maven-web-application&update=true"

    sonarqube:
       runs-on: self-hosted
       needs: BUILD
       steps:
    #  - uses: actions/checkout@v4

    #  - name: Set up JDK 17
    #    uses: actions/setup-java@v4
    #     with:
    #      java-version: '17'
    #       distribution: 'temurin'
    #       cache: maven

       - name: SonarQube Analysis
         run: mvn sonar:sonar


