name: CI-CD-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  BUILD:
    runs-on: [self-hosted, MDP]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

<<<<<<< HEAD
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
=======
      - name: install maven
        run: |
          sudo apt update
          sudo apt install maven -y
>>>>>>> ea732acd14ec282a9e4f064cc8b356752e070d28

<<<<<<< HEAD
      - name: Build WAR file
=======
      - name: Build with Maven
>>>>>>> ea732acd14ec282a9e4f064cc8b356752e070d28
        run: mvn clean package
<<<<<<< HEAD
      
=======
        
      - name: Deploy WAR to Tomcat
        env:
          TOMCAT_URL: ${{ secrets.TOMCAT_URL }}
          TOMCAT_USER: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASS: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          WAR=$(ls target/*.war | head -n 1)
          curl -sS -u "${TOMCAT_USER}:${TOMCAT_PASS}" --upload-file "$WAR" "${TOMCAT_URL}/manager/text/deploy?path=/maven-web-application&update=true"
>>>>>>> ea732acd14ec282a9e4f064cc8b356752e070d28

<<<<<<< HEAD

=======
  sonarqube:
      runs-on: self-hosted
      needs: BUILD
      steps:
    #  - uses: actions/checkout@v4

    #  - name: Set up JDK 17
    #    uses: actions/setup-java@v4
    #     with:
    #      java-version: '17'
    #       distribution: 'temurin'
    #       cache: maven

       - name: SonarQube Analysis
         run: mvn sonar:sonar



>>>>>>> ea732acd14ec282a9e4f064cc8b356752e070d28